<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Process\Process;

class DeployFoodAppCloudFunction extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'foodapp:deploy-cloud-function {database_id : The Firestore database ID (e.g. tidcraft-hareshfood)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Deploy a dedicated Cloud Function v2 trigger for a specific FoodApp tenant Firestore database (Solution 2).';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $databaseId = trim($this->argument('database_id'));
        if (empty($databaseId)) {
            $this->error('A valid database_id is required.');
            return 1;
        }

        $cleanDb = $databaseId;
        $fnName = 'delivery_' . strtolower(preg_replace('/[^a-zA-Z0-9]/', '_', $cleanDb));

        $this->info("=================================================");
        $this->info(" Deploying FoodApp Cloud Function (Solution 2)  ");
        $this->info(" Database: $cleanDb");
        $this->info(" Function: $fnName");
        $this->info("=================================================");

        // Locate functions directory
        $candidates = [
            base_path('products/FoodApp/firebase_functions'),
            base_path('products/FoodApp/backup/Order Tracking Firebase Function'),
            '/home/prodtidcraftcomusr/food-app/firebase_functions',
            '/home/prodtidcraftcomusr/food-app/backup/Order Tracking Firebase Function',
            '/home/devtidcraftcomusr/food-app/firebase_functions',
            '/home/devtidcraftcomusr/food-app/backup/Order Tracking Firebase Function'
        ];

        $functionsDir = null;
        foreach ($candidates as $dir) {
            if (is_dir($dir) && file_exists($dir . '/deploy_tenant.js')) {
                $functionsDir = $dir;
                break;
            }
        }

        if (!$functionsDir) {
            $this->error("Cloud Functions directory with deploy_tenant.js not found.");
            return 1;
        }

        $this->info("Using Functions Directory: $functionsDir");

        $tempDir = sys_get_temp_dir() ?: '/tmp';
        $writableHome = (isset($_SERVER['HOME']) && $_SERVER['HOME'] !== '/var/www' && is_dir($_SERVER['HOME']) && is_writable($_SERVER['HOME']))
            ? $_SERVER['HOME']
            : $tempDir;

        // Use a user-scoped subdirectory under /tmp so config dirs are always
        // owned by the current process user — /tmp/.config may be owned by root.
        $currentUser = get_current_user() ?: (getenv('USER') ?: 'foodapp-deploy');
        $userTmpDir = rtrim($tempDir, '/') . '/' . preg_replace('/[^a-zA-Z0-9_-]/', '_', $currentUser);
        @mkdir($userTmpDir . '/.config', 0755, true);
        @mkdir($userTmpDir . '/.cache', 0755, true);

        $env = [
            'TARGET_TENANT_DB' => $cleanDb,
            'PATH' => (getenv('PATH') ?: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin') . ':/usr/local/bin:/usr/bin:/bin',
            'HOME' => $writableHome,
            'XDG_CONFIG_HOME' => $userTmpDir . '/.config',
            'XDG_CACHE_HOME'  => $userTmpDir . '/.cache',
            'CI' => 'true',
        ];
        if (getenv('USERPROFILE')) {
            $env['USERPROFILE'] = getenv('USERPROFILE');
        }
        if (getenv('GOOGLE_APPLICATION_CREDENTIALS')) {
            $env['GOOGLE_APPLICATION_CREDENTIALS'] = getenv('GOOGLE_APPLICATION_CREDENTIALS');
        }

        // ── PHP writes functions/.env and tenants.json BEFORE calling node ──────
        // When Laravel runs as www-data, the node subprocess may not have write
        // permission to files owned by devtidcraftcomusr. PHP writes them here
        // so Cloud Build always sees the correct FIRESTORE_DB, even if node's
        // own write attempt (in deploy_tenant.js) is blocked by EACCES.
        $fnSubDir = $functionsDir . '/functions';
        $fnEnvFile = $fnSubDir . '/.env';
        $fnTenantsFile = $fnSubDir . '/tenants.json';

        $envWritten = @file_put_contents(
            $fnEnvFile,
            "# Auto-generated by DeployFoodAppCloudFunction — do not edit manually\nFIRESTORE_DB={$cleanDb}\n"
        );
        if ($envWritten !== false) {
            $this->info("[Registry] PHP wrote functions/.env FIRESTORE_DB=\"{$cleanDb}\"");
        } else {
            $this->warn("[Registry Warning] PHP could not write functions/.env (permission denied). Run on server: sudo chown www-data:www-data {$fnEnvFile} && sudo chmod 664 {$fnEnvFile}");
        }

        $tenantsWritten = @file_put_contents(
            $fnTenantsFile,
            json_encode([$cleanDb], JSON_PRETTY_PRINT) . "\n"
        );
        if ($tenantsWritten !== false) {
            $this->info("[Registry] PHP wrote functions/tenants.json = [\"{$cleanDb}\"]");
        } else {
            $this->warn("[Registry Warning] PHP could not write functions/tenants.json (permission denied). Run on server: sudo chown www-data:www-data {$fnTenantsFile} && sudo chmod 664 {$fnTenantsFile}");
        }
        // ─────────────────────────────────────────────────────────────────────

        $command = ['node', 'deploy_tenant.js', $cleanDb];
        $process = new Process($command, $functionsDir, $env);
        $process->setTimeout(600); // 10 minutes timeout for GCP Cloud Build

        $this->info("Executing deployment (this may take 2-4 minutes)...");

        $process->run(function ($type, $buffer) {
            $this->output->write($buffer);
        });

        if (!$process->isSuccessful()) {
            $errorOutput = trim($process->getErrorOutput() ?: $process->getOutput());
            $this->error("Deployment failed: " . $errorOutput);
            return 1;
        }

        $this->info("Function $fnName successfully deployed for database $cleanDb!");
        return 0;
    }
}
